repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: latest
    hooks:
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: latest
    hooks:
      - id: ruff
      - id: ruff-format
{% if cookiecutter.project_base_deps == "sam" -%}
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.15.0
    hooks:
      - id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$
{% endif %}